export class ServiceItem{
    title:string
    slug:string
    category:string
    subcategory?:string
    type:string
    bullet0:string
    bullet1:string
    bullet2?:string
    bullet3?:string
    bullet4?:string
    tileImage:string
    image0:string
    image1?:string
    image2?:string
    image3?:string
    image4?:string
    image5?:string
    image6?:string
    image7?:string
    image8?:string
    image9?:string
    video?:string    
}